korean translation 3.1~3.6 & 5.1 ~ 5.6
goldbergyoni/nodebestpractices pull request #1095
Opened 2021-11-09 00:21 UTC by EverythingAvailable

korean translation through 3.1 to 3.6 and 5.1 and 5.6

2021-11-18 01:18 UTC, uronly14me commented on sections/production/createmaintenanceendpoint.korean.md
> +예를들어, 프로세스의 힙덤프(메모리 스냅샷)를 반환할 수 있으며, 메모리 누수가 있는지에 대해 보고할 수 있으며 심지어는 REPL커맨드를 직접적으로로 실행할 수 있도록 허용한다. 이러한 endpoint는 전통적인 데브옵스 툴들(monitoring products, logs, 등등)이 특정 타입의 정보를 취합하지 못하거나 너가 그런 툴들을 사고/설치하지 않
이 부분은 원문에 맞춰 한 문단으로 작성하는게 어떨까요

2021-11-18 01:18 UTC, uronly14me commented on sections/production/createmaintenanceendpoint.korean.md
> +const heapdump = require("heapdump");
원문에 맞춰 작은 따옴표로 부탁드립니다
```suggestion
const heapdump = require(heapdump);

```

2021-11-18 01:19 UTC, uronly14me commented on sections/production/createmaintenanceendpoint.korean.md
> +    fs.readFile(filename, "utf-8", (err, data) => {
원문에서 잘못 표현한 것 같아서 이것도 작은 따옴표로 부탁드립니다.

2021-11-21 10:43 UTC, goldbergyoni commented
@EverythingAvailable Great work. Note that there are changes in the main, non-korean, readme. Some parts which were meant to show formatting mistakes were changed. Can you exclude changes in non-korean files?

@uronly14me Thanks for reviewing every Korean PR!

@rluvaton Some areas are always formatted by Prettier/editor, let's put there eslint-ignore?

2021-11-21 10:44 UTC, goldbergyoni requested changes

2021-11-21 10:44 UTC, goldbergyoni commented on README.md
> +function someFunction() {
Wrong changes in the English versions,let's exclude non-korean files

2021-11-21 11:24 UTC, EverythingAvailable commented
넵 원본메일 포함 확인하였습니다. 내일 곧바로 수정하여 올려두겠습니다. 리뷰 감사합니다!!

2021년 11월 21일 (일) 오후 7:44, Yoni Goldberg ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/goldbergyoni/nodebestpractices/pull/1095#discussion_r753780840>
> :
>
> > @@ -258,8 +257,7 @@ function someFunction() {
>  }
>
>  // Avoid
> -function someFunction()
> -{
> +function someFunction() {
>
> Wrong changes in the English versions,let's exclude non-korean files
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/goldbergyoni/nodebestpractices/pull/1095#pullrequestreview-811905642>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATJ77C362CUPQIGGPFTQEIDUNDERTANCNFSM5HT7OH6Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-21 11:29 UTC, EverythingAvailable commented
Oh first, thanks for checking these things which need be changed!!
 I just sent you an email written in korean which is wrong message sorry
for that. I'll edit it as soon as i can control it(in 24 hours). Thanks
again!

2021년 11월 21일 (일) 오후 8:24, 이상원 ***@***.***>님이 작성:

> 넵 원본메일 포함 확인하였습니다. 내일 곧바로 수정하여 올려두겠습니다. 리뷰 감사합니다!!
>
> 2021년 11월 21일 (일) 오후 7:44, Yoni Goldberg ***@***.***>님이 작성:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In README.md
>> <https://github.com/goldbergyoni/nodebestpractices/pull/1095#discussion_r753780840>
>> :
>>
>> > @@ -258,8 +257,7 @@ function someFunction() {
>>  }
>>
>>  // Avoid
>> -function someFunction()
>> -{
>> +function someFunction() {
>>
>> Wrong changes in the English versions,let's exclude non-korean files
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/goldbergyoni/nodebestpractices/pull/1095#pullrequestreview-811905642>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATJ77C362CUPQIGGPFTQEIDUNDERTANCNFSM5HT7OH6Q>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-12-08 09:02 UTC, uronly14me commented on sections/codestylepractices/eslint_prettier.korean.md
> +ESLint와 Prettier는 코드 포맷 기능에서 겹치지만 [prettier-eslint](https://github.com/prettier/prettier-eslint), [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), 그리고 [eslint-config-pret
```suggestion
ESLint와 Prettier는 코드 포맷 기능에서 겹치지만 [prettier-eslint](https://github.com/prettier/prettier-eslint), [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), 그리고 [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)와 같은 다른 패키지들을 사용해 쉽게 결합시킬 수 있다. 그들의 차이점에 대해 더 많은 내용은 [링크](https://stackoverflow.com/questions/44690308/whats-the-difference-between-prettier-eslint-eslint-plugin-prettier-and-eslint)를 통해 확인할 수 있다.
```

2021-12-08 09:08 UTC, uronly14me commented on sections/docker/bootstrap-using-node.korean.md
> +우리는 포크들이 그들의 앱을 `CMD 'npm start'`를 이용해 시작하는 코드 예시들을 보는 것에 익숙하지만 이것은 좋은 방식이 아니다. `npm` 바이너리는 시그널들을 너의 앱으로 전송하지 않을 것이며, 이에 우아한 종료(graceful shutdown)는 되지 않는다(참고 [/sections/docker/graceful-shutdown.md]).
```suggestion
우리는 포크들이 그들의 앱을 `CMD 'npm start'`를 이용해 시작하는 코드 예시들을 보는 것에 익숙하지만 이것은 좋은 방식이 아니다. `npm` 바이너리는 시그널들을 너의 앱으로 전송하지 않을 것이며, 이에 우아한 종료(graceful shutdown)는 되지 않는다(참고 [/sections/docker/graceful-shutdown.md]). 당신이 child-process를 사용한다면 예기치 못한 종료의 경우 이들은 너의 호스트에 좀비프로세스를 남긴 채 올바르게 제거되지 않을 것이다. `npm start`는 또한 아무런 이익이 없는 잉여 프로세스를 가지게 될 것이다. 너의 앱을 시작하려면 `CMD ['node', 'server.js']`를 사용하라. 또한 너의 앱이 child-process를 낳는다면 시작할때 `TINI`를 사용하여라.
```

2021-12-08 09:13 UTC, uronly14me commented on sections/docker/restart-and-replicate-processes.korean.md
> +CMD ["pm2-runtime", "indes.js"]
오타인것 같습니다
```suggestion
CMD ["pm2-runtime", "index.js"]
```

2021-12-08 09:14 UTC, uronly14me commented on sections/production/createmaintenanceendpoint.korean.md
> +# 유지 endpoint를 만들어라
```suggestion
# 유지관리용 endpoint를 만들어라

```

2021-12-08 09:16 UTC, uronly14me commented on sections/production/createmaintenanceendpoint.korean.md
> +  // ...
코드는 린트 없이 원문을 따르는게 좋을 것 같습니다.

2021-12-08 09:19 UTC, uronly14me commented on sections/production/delegatetoproxy.korean.md
> +익스프레스를 신봉하여 제공되는 풍부한 미들웨어를 static파일, gzip 인코딩, 쓰로틀링 요청, SSL termination 등과 같은 네트워크와 관련된 업무에 사용하는 것은 그럴싸 해 보이지만 사실은 다르다. 오히려 싱글스레드 모델이기 때문에 장기간동안 CPU를 바쁘게 함으로써 퍼포먼스 저하를 불러올 수 있다. (되새겨 봐라, 노드의 실행모델은 간단
```suggestion
익스프레스를 신봉하여 제공되는 풍부한 미들웨어를 static파일, gzip 인코딩, 요청 쓰로틀링, SSL termination 등과 같은 네트워크와 관련된 업무에 사용하는 것은 그럴싸 해 보이지만 사실은 다르다. 오히려 싱글스레드 모델이기 때문에 장기간동안 CPU를 바쁘게 함으로써 퍼포먼스 저하를 불러올 수 있다. (되새겨 봐라, 노드의 실행모델은 간단한 업무나 동기처리되는 입출력 관련 업무에 최적화되어있다). 차라리 네트워크 일에 특화된 툴을 사용하는 것이 더 나은 접근방법일 것이다. 널리 알려진 툴들로는 nginx와 HAproxy가 있다. 가장 거대한 클라우드 업체도 node.js 프로세스로의 유입 부하를 줄이기 위한 목적으로 이들을 사용한다.

```

2021-12-08 09:23 UTC, uronly14me commented on sections/production/delegatetoproxy.korean.md
> +  > …다음과 같은 함정에 빠지기 쉽다 – 너는 Express와 같은 패키지를 보고 생각할 것이다. "대단해! 어서 시작해 보자" - 너는 코드를 적을것이고, 그리곤 너가 원하는 것을 해주는 어플리케이션을 만들것이다. 이것은 훌륭하며, 솔직히 말해 너는 이미 많은 전투에서 승리를 거둔 것이다. 하지만 노드는 웹서버라는 아주 중요한 사실을 까먹고 너가 서
```suggestion
  > …다음과 같은 함정에 빠지기 쉽다 – 당신은 Express와 같은 패키지를 보고 생각할 것이다. "대단해! 어서 시작해 보자" - 당신은 코드를 적을것이고, 그리곤 당신이 원하는 것을 해주는 어플리케이션을 만들것이다. 이것은 훌륭하며, 솔직히 말해 당신은 이미 많은 전투에서 승리를 거둔 것이다. 하지만 노드는 웹서버라는 아주 중요한 사실을 까먹고 당신은 서버에 앱을 업로드 하거나, HTTP 포트에 연결(listen)한다면 전쟁에선 결국 패배할 것이다. **어떤 양의 트래픽이든 당신의 애플리캐이션에 유입되기만 하면 당신은 무언가 잘못되기 시작했음을 알아차릴 것이다: 연결은 끊기고, asset의 서비스는 중단되며 심할경우 당신의 서버는 죽어버린다. 이는 이 일에 대해 증명된 웹서버가 잘 처리하는 복잡한 일들을 노드에게 처리하도록 하는 꼴이다. 왜 바퀴를 새로만드는가?**
  > **노드는 하나의 요청, 하나의 이미지 용이다. 그리고 이것(노드)은 너의 애플리케이션이 데이터베이스를 읽어들이거나 복잡한 로직을 다루는 등의 중요한 일처리를 할 때 사용할 수 있는 메모리라는 것을 명심해라. 왜 편리함을 위해 너의 애플리케이션을 불구로 만들어 버리는 것인가?**

```

2021-12-17 08:44 UTC, uronly14me approved these changes

2021-12-17 08:47 UTC, uronly14me commented
@goldbergyoni 
Hi, it looks good to me!

2022-02-20 14:49 UTC, merged

2022-02-20 14:53 UTC, goldbergyoni commented
@EverythingAvailable Awesome contribution. Thanks for making this guide better ❤️

@all-contributors please add @EverythingAvailable  for content