fix the latest version
goldbergyoni/nodebestpractices pull request #1097
Opened 2021-11-09 05:25 UTC by qlsdl9516

2021-11-10 17:41 UTC, rluvaton requested changes

2021-11-10 17:41 UTC, rluvaton commented on sections/testingandquality/3-parts-in-name.md
> -# Include 3 parts in each test name
Hey, thanks for the contribution! I see you mistakenly changed the English version instead of the Korean one

2021-11-10 17:41 UTC, rluvaton commented on sections/testingandquality/aaa.md
> -# Structure tests by the AAA pattern
Hey, thanks for the contribution! I see you mistakenly changed the English version instead of the Korean one :)

2021-11-13 16:27 UTC, rluvaton commented
Hey @qlsdl9516, thank for your contribution!

Just wanted to make sure you saw my review - you accidentally changed the English version instead of the Korean one


And also, could you please rename this PR title so it will much the PR changes?

2021-11-21 08:34 UTC, goldbergyoni commented
@qlsdl9516 See @rluvaton comment:)

2021-12-17 08:49 UTC, uronly14me commented
@qlsdl9516 수빈님 영어 원본을 잘 못 수정한 것 같습니다.

2022-04-27 16:41 UTC, closed without merging