Update README.md
goldbergyoni/nodebestpractices pull request #761
Opened 2020-08-29 05:24 UTC by Dheeraj-01

change QA to Quality assurance(QA)
At Line Number: 593 of README.md
QA will thoroughly test the code and approve a version that will behave differently in production. Even worse, different servers in the same production cluster might run different code
---------->>>>
Quality assurance(QA) will thoroughly test the code and approve a version that will behave differently in production. Even worse, different servers in the same production cluster might run different code

2020-08-29 18:33 UTC, Archangel-Ambriel approved these changes

2020-09-03 15:05 UTC, uchibeke approved these changes
♠️ LGTM. Makes it easier for beginners to understand what is being said.

2020-09-09 10:15 UTC, goldbergyoni commented
@Dheeraj-01 Welcome, and also thanks:)

There is a strong trend of moving most of the testing to developers. I wonder whether we should trade the word "QA" with "You"

@kevynb @BrunoScheufler Thoughts?

2020-09-09 10:57 UTC, BrunoScheufler commented
@goldbergyoni yeah from a responsibility point of view developers should be the people to manage dependencies and tests, QA is just another stage of work following regular development.

2020-09-17 12:19 UTC, goldbergyoni commented
@Dheeraj-01 Are you to phrasing this to be more developer oriented? If busy now, this is absolutely now, we can start with your fix and enhance a bit latter

2020-09-17 13:35 UTC, Dheeraj-01 commented
@goldbergyoni   It's ok for now. You can merge/fix that Readme. After merging, I will develop more.🧐

2020-12-10 22:22 UTC, samuei reviewed
Would it look cleaner to put a space before the parenthetical?

2020-12-24 11:10 UTC, goldbergyoni approved these changes
LGTM

2020-12-24 11:11 UTC, goldbergyoni requested changes
Kindly put a space before the parenthesis, thank you 😉

2021-02-06 19:41 UTC, goldbergyoni commented
@Dheeraj-01 We are one step shy from merging this great contribution and getting your name on the wall.

Let's finalize the last mile?

2021-02-15 02:41 UTC, krychaxp approved these changes

2021-06-20 13:16 UTC, closed without merging